# Configuration
title: Michel Krispin
email: michel.krispin@gmail.com
description: >-
  Overview of my side projects located at <a href='https://github.com/MichelKrispin'>GitHub</a>.
  <br/>
  If you want to get in touch, please drop me an email at <i>michel [dot] krispin [at] gmail [dot] com</i>.
baseurl: ''
url: ''
github_username: MichelKrispin

# Build settings
remote_theme: riggraz/no-style-please
plugins:
  - jekyll-feed

theme_config:
  appearance: 'auto' # "light", "dark" or "auto"
  show_description: true
